jasypt:
      encryptor:
               password: vx-app-HLFZ
spring:
  application:
    name: for-love
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/wx-app?userSSL=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    username: ENC(+U+4Dd/iASb0WuHNdP9KXQ==)
    password: ENC(mzbkwYpebozdnua1hEOdWg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200
  port: 8080
mybatis:
  type-aliases-package: com.hz.love.dao
  mapper-locations: classpath:mapper/*.xml

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
logging:
  level: 
       com.hz.love: debug
  config:
        classpath:log4j2_dev.xml
feign:
     user-client: https://api.weixin.qq.com
     appid: ENC(sDkhl2TUp4be8cCyyKr7aZ85nCGBwGoX/KQaDoT8dyQ=)
     app-secret: ENC(kpGXBeca+M49bhCXWF5miM7LyK6gJuKua6cw1zXS3kqwOngz8QgMrWUYvXNspV+P)
ftp:
    enabled: true
    host: 192.168.1.70
#    host: 192.168.1.108
    port: 5211
#    port: 5210
    username: Ftp-U
    password: ENC(F+e36hrnT/iJa8gbQerevZhjNzlsdTkQ)
    encoding: UTF-8
file:
    upload_path: /wx-app/HLFZ 
       
edition: dev
